#ifndef TEMPLATE_H
#define TEMPLATE_H

const char html_template[] = "\n"
"<!DOCTYPE html>\n"
"<html lang=\"pt\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap\" rel=\"stylesheet\">\n"
"  <title>House Control</title>\n"
"  <style>\n"
"    body { margin: 0; padding: 0; font-family: 'Roboto', sans-serif; background: #f0f2f5; }\n"
"    .container { max-width: 600px; margin: 50px auto; background: #ffffff; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); padding: 20px; }\n"
"    h1, h2 { text-align: center; color: #333333; }\n"
"    .control-section { margin: 20px 0; }\n"
"    .control-section p { text-align: center; margin: 10px 0; }\n"
"    .button { display: inline-block; padding: 12px 24px; margin: 5px; border: none; border-radius: 4px; background: #6200EE; color: #ffffff; text-decoration: none; font-weight: 500; transition: background 0.3s ease; }\n"
"    .button:hover { background: #3700B3; }\n"
"    .status { font-size: 0.9em; color: #555555; text-align: center; margin-top: 20px; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"container\">\n"
"    <h1>House Control</h1>\n"
"    <div class=\"control-section\">\n"
"      <h2>LEDs (Cômodos)</h2>\n"
"      <p>Sala (LED 1): <a class=\"button\" href=\"/led1/on\">Ligar</a> <a class=\"button\" href=\"/led1/off\">Desligar</a></p>\n"
"      <p>Cozinha (LED 2): <a class=\"button\" href=\"/led2/on\">Ligar</a> <a class=\"button\" href=\"/led2/off\">Desligar</a></p>\n"
"      <p>Quarto (LED 3): <a class=\"button\" href=\"/led3/on\">Ligar</a> <a class=\"button\" href=\"/led3/off\">Desligar</a></p>\n"
"    </div>\n"
"    <div class=\"control-section\">\n"
"      <h2>Buzzer (Alarme)</h2>\n"
"      <p><a class=\"button\" href=\"/buzzer/on\">Ativar</a> <a class=\"button\" href=\"/buzzer/off\">Desativar</a></p>\n"
"    </div>\n"
"    <div class=\"control-section\">\n"
"      <h2>Status</h2>\n"
"      <p>Sensor A: %s</p>\n"
"      <p>Botão B: %s</p>\n"
"    </div>\n"
"  </div>\n"
"</body>\n"
"</html>\n"
"";

#endif // TEMPLATE_H
